const homedb=[
    {  name:"Ram",
       address:"21,ABC street,Chennai.",
       contact:"9213454344",
       category:"Rent",
       budget:5000,
       BHK:"1BHK",
       possession:"Ready To Move",
       type:"Residential Apartment",
       postedby:"Owner",
       furnishinfo:"Furnished",
       availability:"Family",
       age:"1-5 years old", 
    },
    {  name:"Ravindranath",
    address:"22,ZXY street,Chennai.",
    contact:"9877631313",
    category:"Rent",
    budget:5000,
    BHK:"1RK",
    possession:"Ready To Move",
    type:"Residential Apartment",
    postedby:"Owner",
    furnishinfo:"Furnished",
    availability:"Family",
    age:"1-5 years old", 
    },
    {
        name:"Ram",
       address:"21,ABC street,Chennai.",
       contact:"9213454344",
        category:"Rent",
        budget:3000,
        BHK:"1BHK",
        possession:"Ready To Move",
        type:"Residential Apartment",
        postedby:"Owner",
        furnishinfo:"SemiFurnished",
        availability:"Bachelor",
        age:"1-5 years old", 
    },
    {name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Rent",
        budget:4500,
        BHK:"1BHK",
        possession:"Ready To Move",
        type:"Serviced Apartments",
        postedby:"Builder",
        furnishinfo:"UnFurnished",
        availability:"Bachelor",
        age:"1-5 years old", 
    },
    {  name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Rent",
        budget:8000,
        BHK:"2BHK",
        possession:"Ready To Move",
        type:"Serviced Apartment",
        postedby:"Owner",
        furnishinfo:"Furnished",
        availability:"Family",
        age:"5-10 years old", 
    },
    {  name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Rent",
        budget:12000,
        BHK:"3BHK",
        possession:"Ready To Move",
        type:"Farm House",
        postedby:"Owner",
        furnishinfo:"Furnished",
        availability:"Bachelor",
        age:"1-5 years old", 
    },
    {  name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Rent",
        budget:20000,
        BHK:"+3BHK",
        possession:"Ready To Move",
        type:"Residential Apartment",
        postedby:"Owner",
        furnishinfo:"Furnished",
        availability:"Family",
        age:"1-5 years old", 
    },
    {  name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Rent",
        budget:5000,
        BHK:"1BHK",
        possession:"Ready To Move",
        type:"Farm House",
        postedby:"Owner",
        furnishinfo:"Furnished",
        availability:"Family",
        age:"1-5 years old", 
    },
    {  name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Buy",
        budget:15000,
        BHK:"1BHK",
        possession:"Ready To Move",
        type:"Residential Apartment",
        postedby:"Owner",
        furnishinfo:"Furnished",
        availability:"Family",
        age:"1-5 years old", 
    },
    {  name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Buy",
        budget:15000,
        BHK:"2BHK",
        possession:"Ready To Move",
        type:"Farm House",
        postedby:"Owner",
        furnishinfo:"Furnished",
        availability:"Bachelor",
        age:"1-5 years old", 
    },
    {  name:"Ram",
    address:"21,ABC street,Chennai.",
    contact:"9213454344",
        category:"Rent",
        budget:45000,
        BHK:"1BHK",
        possession:"In 1 Year",
        type:"Residential Apartment",
        postedby:"Owner",
        furnishinfo:"Furnished",
        availability:"Family",
        age:"1-5 years old", 
    },

]
export default homedb;